### ISSUE TITLE
Adapt Mendeley workers to Oauth2 API

### ISSUE THREAD

**Issue by tsujigiri** [gedankenstuecke/snpr#117]
The Mendeley workers are currently disabled as the old API has been switched off. To make them work again we need to make them use the new Oauth2 API.

**Comment by philippbayer** [comment]
Looking at the API documentation, this still hasn't happened, and I doubt it will happen. For now the workers are off anyway to alleviate some of the load on the system and we got "most" of the annotation. So go ahead without full text search?

This might help too: https://github.com/Mendeley/mendeley-api-ruby-identifier-catalog-search

**Comment by gedankenstuecke** [comment]
Ack, works for us so far. :)
