### ISSUE TITLE
https://opensnp.org/users.json not working.

### ISSUE THREAD

**Issue by richhl** [gedankenstuecke/snpr#156]
curl https://opensnp.org/users.json

shows:

{"error":"Sorry, we couldn't find any users"}

thx in advance

**Comment by tsujigiri** [comment]
Thank you very much for reporting! We will look into it as soon someone finds the time. :)

**Comment by gedankenstuecke** [comment]
It's fixed. :-)

**Comment by richhl** [comment]
thx. it's working
