### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/snpr#157]
https://opensnp.org/data/zip/opensnp_datadump.current.zip right now gives a 403, seems to be something off with the default permissions when created.

**Comment by gedankenstuecke** [comment]
okay, it's not a permission issue in itself. the file itself just doesn't exist :open_mouth:

**Comment by tsujigiri** [comment]
[This](https://opensnperr.herokuapp.com/apps/53faacfe1132c71f92000001/problems/5520d6b8e362a6dda100002a) might have something to do with it.

**Comment by gedankenstuecke** [comment]
I tried to investigate it a bit further. So the zipfulldata job dies somewhere in the zip_genotype_file thing (https://github.com/gedankenstuecke/snpr/blob/master/app/workers/zipfulldata.rb#L50), as the zip file itself is created and it contains some of the genotyping files, but the overall archive is broken and the symlink isn't redirected. I'm a bit out of ideas on why this is the case right now.

**Comment by philippbayer** [comment]
Could be a bug in rubyzip, this person has the same problem: https://www.ruby-forum.com/topic/211146

**Comment by gedankenstuecke** [comment]
We also had this problem earlier:
https://github.com/rubyzip/rubyzip/issues/82 (just ctrl-f for your own name
;-)).

**Comment by philippbayer** [comment]
haha yeah :D I totally forgot about it. back then it was an issue with file size, there was a "maximum" for rubyzip that later versions upped/removed, maybe we hit the same thing again?

**Comment by philippbayer** [comment]
It could also of course be that we have some dangling phenotype/genotyping/picture_phenotype/etc. with some Nil as an attribute somewhere in the db

**Comment by gedankenstuecke** [comment]
That might be, but seems unlikely to me as the problem did arise pretty much in time with the rails update :D

**Comment by tsujigiri** [comment]
We could try using the regular release of rubyzip again. We pinned it to master. This could also be broken because I updated all the gems and hence, this one was also updated to the latest master commit.

**Comment by tsujigiri** [comment]
See #160

**Comment by philippbayer** [comment]
Let's deploy and have a look

**Comment by gedankenstuecke** [comment]
Playing with :fire: :D

**Comment by philippbayer** [comment]
Deployed - did it burn down yet? Do you have a testcase?

**Comment by tsujigiri** [comment]
We can mark it resolved in Errbit and see if it comes back.

**Comment by philippbayer** [comment]
btw, pry is still being weird on production:
(as snpr)

```
>bundle exec rake dump:full                                                                                                              deploy 
rake aborted!
LoadError: cannot load such file -- pry
/srv/www/snpr/.rvm/gems/ruby-2.2.1-railsexpress@global/gems/bundler-1.8.4/lib/bundler/runtime.rb:76:in `require'
```

even though it's not in production env

**Comment by gedankenstuecke** [comment]
Run the zipfulldata-job once. :-)

**Comment by tsujigiri** [comment]
`RAILS_ENV=production`?

**Comment by philippbayer** [comment]
Herpderp that fixed it. zipfulldata running right now

**Comment by gedankenstuecke** [comment]
It will take some time before you can tell. It crashed in the last steps. ;)

**Comment by tsujigiri** [comment]
You also could have waited for the tests to pass... ;) https://travis-ci.org/tsujigiri/snpr/builds/58463832

**Comment by tsujigiri** [comment]
Restarted it, now it's green.

**Comment by tsujigiri** [comment]
The error is still there.

**Comment by gedankenstuecke** [comment]
Okay, maybe it really is a single file that causes the crash?

**Comment by philippbayer** [comment]
I've added a bunch of logging to the job to pinpoint a bit more which of the methods actually crashes, deployed, let's see what happens

**Comment by gedankenstuecke** [comment]
Awesome. Will be in Paris until Sunday afternoon for the Sage Assembly, with limited access to the internet. Will look into once I'm back in my office.

**Comment by philippbayer** [comment]
It's a mystery:

```ruby
Zip::File.open(zip_fs_path, Zip::File::CREATE) do |zipfile|
   #lots of stuff
   zip_genotype_files(genotypes, zipfile)
   log "6/6 Finished zipping genotype file"
end
log "Chmodding public zip"
```

The last line in the logs before the job crashes is "6/6 Finished zipping genotype file" - even though there's "just" an end there, "Chmodding public zip" does not appear.

That makes me think that this is not an issue with our data but with rubyzip.

**Comment by gedankenstuecke** [comment]
Or it really is a problem with the files we're trying to zip? What happens when you try to manually create the zip file?

**Comment by philippbayer** [comment]
I think I fixed it! But it's one of those fixes that make you wonder why it worked in the first place...
rubyzip does not use zip64 by default since not all unzippers can handle zip64. So by default, it uses "normal" zip, which has a size limit of 4GB.
For some reason in the past it seems to have used zip64 but upgrading everything seems to have "reset" it to standard zip. 

I've ran the zipping job manually in the console with zip64 and unicode enabled and that worked, I've added a new file to config/initializers so hopefully in about 3-4 hours we'll know whether it's fixed completely

**Comment by gedankenstuecke** [comment]
Great. I'll keep my fingers crossed that it works out.

**Comment by philippbayer** [comment]
:neckbeard: 
https://opensnp.org/data/zip/opensnp_datadump.current.zip

**Comment by tsujigiri** [comment]
:clap:

**Comment by gedankenstuecke** [comment]
:+1: Very nice! I will answer all the support questions about this then. :-)
