### ISSUE TITLE
Create dumps in regular intervals instead of on demand

### ISSUE THREAD

**Issue by tsujigiri** [gedankenstuecke/snpr#159]
Instead of creating a full dump or picture dump whenever a user wants one, we should have a cron job doing that on a daily or so basis. We also wouldn't need to send an email then but just have the download link on the page. We should also clean up old dumps, so we don't fill our disk space with them.

**Comment by philippbayer** [comment]
Isn't that what config/schedule.rb was supposed to do via "whenever"?

**Comment by tsujigiri** [comment]
Right. We should do this with the picture dump as well, though.

**Comment by gedankenstuecke** [comment]
Yes, I think so.

**Comment by philippbayer** [comment]
Doesn't the zipfulldata job already run the picturedump too in ```create_picture_zip()```? And that job is run daily, looking at public/data/zip, successfully too

**Comment by tsujigiri** [comment]
OK. I assumed because the jobs were accumulating and created a gazillion dumps over the past weeks. I had to keep the disk from running out of space. Let's set the retries to 0 and remove old dumps once we successfully created a new one.

**Comment by gedankenstuecke** [comment]
Right, removing old files right now isn't done automatically.

**Comment by philippbayer** [comment]
What do you think of 7f3df75?

I've tested it a bit with old files and it seems to delete the correct files. 

To make an old zip file:
     touch --date="Sun, 29 Feb 2004 16:21:42 -0800" public/data/zip/blabla.zip

**Comment by gedankenstuecke** [comment]
I think we are now a bit overzealous in deleting stuff. the opensnp_datadump.current.zip now was removed as well :D

**Comment by philippbayer** [comment]
lol

It is in the list of forbidden_files and wasn't deleted on my system... hmmmmm let me check

**Comment by gedankenstuecke** [comment]
I for now manually created the symlink because a user wanted the download.

**Comment by philippbayer** [comment]
so the zip is there just the link was deleted?

**Comment by gedankenstuecke** [comment]
yes, but the zip-file itself is the one that contains the creation date in the name. and the stable download-link is the symlink to it, named opensnp_datadump.current.zip (and that one was gone)

**Comment by philippbayer** [comment]
OK added a tiny extra check to check that only files, not links, get deleted in 219c1dc
deploying

**Comment by gedankenstuecke** [comment]
Great, thanks a lot :-)

**Comment by philippbayer** [comment]
OK the genotyping is still there, closing this issue. Dumps are now created regularly and old data is deleted
