### ISSUE TITLE
"Download the data!" button links to 404 page

### ISSUE THREAD

**Issue by stiegenaufgang** [gedankenstuecke/snpr#162]
The "Download the data!" button on your homepage links to an error page.

**Comment by philippbayer** [comment]
Thank you for reporting this!
We've recently implemented an "auto clean up" step at the end of the genotyping zipping worker which seems to still have some hiccups - right now the link works for me: https://opensnp.org/genotypes

Did you use a different link or is this the same one?

**Comment by philippbayer** [comment]
Aaah now I see the link you meant, it's only visible to users who aren't logged in which is why we haven't seen it, I've fixed it in 24a0eca.
For me, after a refresh of the landing page the link works

**Comment by stiegenaufgang** [comment]
Thanks for the quick reply, it's working now.
