### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by tsujigiri** [gedankenstuecke/snpr#168]
In the past we added every new feature that came to our minds, which has lead to a lot of messy, untested code. I would like to see this improve. For this, I think we should agree on at least some form of process regarding what code gets to be added. One thing we could do is proper code reviews, where no one pushes directly to master, but opens a pull request and at least on other developer looks over it and points out that there are tests missing... ;)

I'm not quite sure what to do about [feature creep](https://en.wikipedia.org/wiki/Feature_creep), though. I guess the same rules should apply: Every new feature is discussed in an issue first and we decide if it is really neccessary, if it can wait, or if we can live without it.

What do you think? Do you have other ideas?

**Comment by gedankenstuecke** [comment]
Being one of the main people responsible for all that untested code making it into new features: I wholeheartedly agree, doing reviews w/o directly pushing to master is a thing we should do. :smiley: 

For the features I'm a bit on the fence. Doesn't code review necessarily lead to people looking over newly added features before going live with them?

**Comment by philippbayer** [comment]
Pull-requests for everyone sounds like a good idea, that gives the automated complainer a chance too. We haven't had new features in quite a while, maybe we stop having new features until X% test coverage is reached?

**Comment by tsujigiri** [comment]
@gedankenstuecke New features don't just have to be developed, though, they also have to be maintained, which is especially hard when untested. We saw the consequences of that when we upgraded to Rails 4. A lot of the untested code broke without us noticing before we deployed it.

So, aiming at a certain test coverage might be a good idea. Definitely we shouldn't add or change any code without tests. Pull requests hopefully add some social pressure, too. ;)

**Comment by gedankenstuecke** [comment]
As we may have more new people contribute in the future: shall we codify this somewhere?

**Comment by tsujigiri** [comment]
Probably! :)

**Comment by gedankenstuecke** [comment]
I'll try to find the time for some editing of the README later tonight. :)

**Comment by gedankenstuecke** [comment]
Ok, that was not exactly "later tonight" but better late then never, right? 😂

**Comment by tsujigiri** [comment]
:honeybee:

**Comment by gedankenstuecke** [comment]
:bee:'n there, done that :wink:
