### ISSUE TITLE
Only allow one job to access user_snps at a time

### ISSUE THREAD

**Issue by tsujigiri** [gedankenstuecke/snpr#171]
Currently I see two long-running jobs that access user_snps: Parsing and DeleteGenotype. Both started "about 5 hours ago". I guess it would make sense to find out if there are more and put them all on one queue, limited to one job at a time.

**Comment by gedankenstuecke** [comment]
Agree! It also would be good if the delete-job would cancel a parsing-job for the same genotype-ID. :smile:

**Comment by tsujigiri** [comment]
Not sure how to cancel one job from another job, but definitely worth looking into.

**Comment by tsujigiri** [comment]
I'll close this then...
