### ISSUE TITLE
Partition the user_snps table

### ISSUE THREAD

**Issue by tsujigiri** [gedankenstuecke/snpr#173]
The user_snps table is approaching 1 billion rows, which leads to importing things into it taking several hours. Recently it fails a lot due to memory allocation errors, that may or may not be related to data corruption.

But despair not! Rescue is nigh!

What we can do, and what I refrained from so far, is [partitioning](http://www.postgresql.org/docs/9.2/interactive/ddl-partitioning.html) the table. It actually is the obvious thing to do, but Postgres doesn't make it as simple as e.g. MySQL does. But I guess we can't procrastinate this forever. ;)

My idea is, that we make a partition per genotype. This way we save the largest and currently almost always failing step of shoveling the data from the temporary table into the actual table. Instead we basically keep the temporary tables as partitions. We then also don't need the genotype_id column anymore. Parsing would become a matter of seconds instead of hours. The same goes for deleting a genotype's user-SNPs, we simply drop the table and they are gone.

What we need to do beforehand is figure out what information we actually need from that table and how to retrieve it when the table is partititoned. E.g. we need the number of user-SNPs per SNP which means one row from each table. We will have to dig into that. We could, for example, keep track of that in the snps table.

It would also be great if we can find a strategy that let's us first change the Parsing worker, so it already stores the new data to the partitions while we migrate the old data. It might even be a better idea to just parse all the files again instead of dealing with the humongous user_snps table.

I will start with the Parsing worker and try to figure out how to make it do the partitioning.

**Comment by philippbayer** [comment]
That sounds like a great idea and would certainly enable to bring back the "Your SNPs" tab, finally ;)

So we'll have a user_snps "master" table and one partition per genotyping? I think that would be better than one partition per user as then some users with multiple genotypings will have slower performance than users with only one genotyping.

Parsing everything again and just dropping the old data would be preferable, we'd get rid of any corruption, and we would ensure that genotypings that were parsed with older versions of the Parsing jobs have consistent database entries compared to newer genotypings.

This gem may be very helpful: https://github.com/inocode/partitioned (keep in mind that this is a fork, the original project seems to be dead)
From these slides: http://www.slideshare.net/agnessa/table-partitioning-in-postgre-sql-rails

**Comment by tsujigiri** [comment]
[So far so good...](https://github.com/gedankenstuecke/snpr/compare/master...tsujigiri:partition-user_snps) Parsing works.

**Comment by tsujigiri** [comment]
As stated [here](https://github.com/gedankenstuecke/snpr/pull/175#issuecomment-105159804), I started moving the Genotype-Snp association into Postgres array/hstore columns. Since I was on vacation, not much has happened since then. I'm continuing working on this.

**Comment by tsujigiri** [comment]
Closing this, work continues over at #187.
