### ISSUE TITLE
updating avatar results in "you must be logged out to access this page"

### ISSUE THREAD

**Issue by audy** [gedankenstuecke/snpr#183]
When I attempt to update my avatar, I get redirected to my user page with the flash error message "you must be logged out to access this page."

I think the error starts [here](https://github.com/gedankenstuecke/snpr/blob/03f4f14df3e4fea99ef9a97db4363956b21d7da6/app/controllers/users_controller.rb#L161-L168) in `UsersController`. The flash message comes from [here](https://github.com/gedankenstuecke/snpr/blob/03f4f14df3e4fea99ef9a97db4363956b21d7da6/app/controllers/application_controller.rb#L31-L38) in `ApplicationController`. I'm not sure why this is happening. Perhaps someone could check the logs and comment with a Traceback.

Related: are there plans to add integration testing? If it helps, I could add some integration testing framework (in a separate issue) and writing a (failing) spec for this.

**Comment by tsujigiri** [comment]
I'll take a look.

> are there plans to add integration testing?

We use RSpec with Capybara for this. Tests go to `spec/features`.

**Comment by philippbayer** [comment]
This is what happens in the logs:

```
Started PATCH "/users/1" for 127.0.0.1 at 2015-11-04 16:09:06 +0800
Processing by UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "user"=>{"avatar"=>#<ActionDispatch::Http::UploadedFile:0x007fa715c91cd8 @tempfile=#<Tempfile:/tmp/RackMultipart20151104-13856-ps2cg6.png>, 
@original_filename="Image.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"Image.png\"\r\nContent-Type: imag
e/png\r\n">, "name"=>"dwada", "sex"=>"rather not say", "yearofbirth"=>"rather not say", "description"=>"", "message_on_newsletter"=>"1", "message_on_message"=>"1", "mes
sage_on_new_phenotype"=>"0", "message_on_phenotype_comment_reply"=>"1", "message_on_snp_comment_reply"=>"1"}, "commit"=>"Updating...", "id"=>"1"}
Can't verify CSRF token authenticity
  ESC[1mESC[35mUser Load (0.3ms)ESC[0m  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
Redirected to http://localhost:3000/signin
Filter chain halted as :require_owner rendered or redirected
Completed 302 Found in 3ms (ActiveRecord: 0.3ms)


Started GET "/signin" for 127.0.0.1 at 2015-11-04 16:09:06 +0800
Processing by UserSessionsController#new as HTML
  ESC[1mESC[36mUser Load (0.4ms)ESC[0m  ESC[1mSELECT  "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT 1ESC[0m
  ESC[1mESC[35mUser Load (0.2ms)ESC[0m  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
Redirected to http://localhost:3000/users/1
Filter chain halted as :require_no_user rendered or redirected
Completed 302 Found in 6ms (ActiveRecord: 0.6ms)
```

Looks like a redirect from :require_owner to the /signin page, and then the /signin page complains  because the user is obviously logged in.

I wonder why :require_owner fires in the first place.

**Comment by philippbayer** [comment]
See PR #211

**Comment by philippbayer** [comment]
Fixed now

**Comment by audy** [comment]
Worked for me. Thanks!

**Comment by philippbayer** [comment]
Thanks for checking :+1:
