### ISSUE TITLE
Calvyn82: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by Calvyn82** [gedankenstuecke/snpr#194]
Heard about the project from a buddy who attended Strange Loop. I have some experience in Rails. Happy to help out wherever I can.<p><br><blockquote>This issue was created by @Calvyn82 via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by philippbayer** [comment]
Great! Thank you very much for helping out :)

I think the first start would be to add tests and raise coverage, see #192. @tsujigiri has been working on implementing a different data structure to store user-SNPs in order to speed up parsing - have a look at #189 

Furthermore, you can always pretty up the place, see #191  :neckbeard:

**Comment by Calvyn82** [comment]
I got the app up and running on localhost.

So, I ran the test suite and got 26 examples with 21 failures. Do I have something set up wrong, or do we just have our work cut out for us?

**Comment by philippbayer** [comment]
What are the failures? Does the server start normally? It could be that you're just missing a running redis-server

**Comment by tsujigiri** [comment]
Welcome, @Calvyn82!

Btw., do we want to actually merge #191, #192, and #193 at some point? :)

**Comment by gedankenstuecke** [comment]
@tsujigiri yes, I'm all for merging at some point. :)

@Calvyn82: cool, in which context did your buddy hear about openSNP at Strange Loop? :-)

**Comment by Calvyn82** [comment]
Sorry, I had to get some sleep.

@philippbayer I have redis-server up and running, but it's my first time using it. Do I need to point it at a particular configuration file?

@gedankenstuecke He attended this talk, and then we looked for a Ruby or Rails project. https://www.youtube.com/watch?v=hKVUFL9clZo&feature=youtu.be&a

**Comment by Calvyn82** [comment]
I have redis-server up and running in the background. I have bin/rails s running in another pane.
I have sidekiq and all of the others running in one more pane.

When I run bin/rake I get the following error.

/home/clayton/.rubies/ruby-2.2.3/bin/ruby -I/home/clayton/.gem/ruby/2.2.3/gems/rspec-core-3.2.3/lib:/home/clayton/.gem/ruby/2.2.3/gems/rspec-support-3.2.2/lib /home/clayton/.gem/ruby/2.2.3/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
git://github.com/tsujigiri/mendeley.git (at paging_search) is not yet checked out. Run `bundle install` first.
/home/clayton/.rubies/ruby-2.2.3/bin/ruby -I/home/clayton/.gem/ruby/2.2.3/gems/rspec-core-3.2.3/lib:/home/clayton/.gem/ruby/2.2.3/gems/rspec-support-3.2.2/lib /home/clayton/.gem/ruby/2.2.3/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

When I run bundle exec rake or bin/rspec, I get 21 failures in 26 tests. They all have the same basic error.

Failure/Error: build(:snpedia_paper, url: 'http://www.snpedia.com/index.php/Rs1234(A;C)')
     ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  relation "snpedia_papers" does not exist
       LINE 5:                WHERE a.attrelid = '"snpedia_papers"'::regcla...
                                                 ^
       :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                       FROM pg_attribute a LEFT JOIN pg_attrdef d
                         ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                      WHERE a.attrelid = '"snpedia_papers"'::regclass
                        AND a.attnum > 0 AND NOT a.attisdropped
                      ORDER BY a.attnum

Followed by a stack trace.

I'll look at it some more in a while.

**Comment by tsujigiri** [comment]
Did you `bundle exec rake db:setup` to set up the database?

**Comment by Calvyn82** [comment]
Well, that's embarrassing.

I ran `db:create`, `db:migrate` and `db:seed`. Thought that would cover everything.

Running `bundle exec rake db:setup` fixed the broken tests.

**Comment by tsujigiri** [comment]
Instead of `db:migrate` it is usually better to run `db:schema:load` (which `db:setup` does), since migrations are not intended to work forever, as the code they potentially run changes over time.
