### ISSUE TITLE
Factory Girl?

### ISSUE THREAD

**Issue by Calvyn82** [gedankenstuecke/snpr#196]
Is it okay if I add Factory Girl to the gemspec and start writing some tests using it?

https://github.com/thoughtbot/factory_girl

It'll make it easier to test models and controllers in particular.

**Comment by Calvyn82** [comment]
Never mind. It's in the gemspec. It's just not being used. I'm going to start building some factories.

**Comment by Calvyn82** [comment]
I see. It's being used in the test directory, instead of the spec directory.

**Comment by tsujigiri** [comment]
Yeah, we should probably move the factories over into the spec directory. The tests in the test directory are deprecated anyway and are intended to be replaced by rspec tests. We should probably also add this information the the "Contribute" section of the README. :)

**Comment by Calvyn82** [comment]
If you want, I can start moving the factories over and making a separate factory file for each model. 

I don't have a key for the apis yet, so I can't use them, but I can get started.

**Comment by tsujigiri** [comment]
That would be pretty awesome! :)
