### ISSUE TITLE
clean up papers

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/snpr#202]
I noticed that we have tons of duplicates amongst the papers in our DB. E.g. https://opensnp.org/snps/rs9939609#plos

Here basically all papers there are listed at least twice. We should maybe go through each paper category once and check for duplicate names.

**Comment by tsujigiri** [comment]
Do we maybe import papers that reference more than one SNP once for each of the SNPs?

**Comment by gedankenstuecke** [comment]
I think originally we didn't, or at least then they should be only keyed to one SNP and not multiple ones at the same time. So I guess at some point the parser went wrong and started collecting papers multiple times for one SNP.

**Comment by philippbayer** [comment]
The absurd thing is that they all have the same ID in the database:

``` ruby
Snp.find_by_name("rs9939609").plos_papers.each do |u|
   if u.first_author.include? "Yan Guo"
     puts u.inspect
   end
end; nil
```
says

```
#<PlosPaper id: 1284, first_author: "Yan Guo", title: "The Fat Mass and Obesity Associated Gene, FTO, Is ...", doi: "10.1371/journal.pone.0027312", pub_date: "2011-11-18 00:00:00", created_at: "2012-02-06 00:12:36", updated_at: "2014-10-30 16:08:59", reader: 3786>
#<PlosPaper id: 1284, first_author: "Yan Guo", title: "The Fat Mass and Obesity Associated Gene, FTO, Is ...", doi: "10.1371/journal.pone.0027312", pub_date: "2011-11-18 00:00:00", created_at: "2012-02-06 00:12:36", updated_at: "2014-10-30 16:08:59", reader: 3786>
#<PlosPaper id: 1284, first_author: "Yan Guo", title: "The Fat Mass and Obesity Associated Gene, FTO, Is ...", doi: "10.1371/journal.pone.0027312", pub_date: "2011-11-18 00:00:00", created_at: "2012-02-06 00:12:36", updated_at: "2014-10-30 16:08:59", reader: 3786>
and 8 more identical lines
```

These all have the same doi so I would have assumed that the worker's ```find_or_initialize_by_doi()``` would return these but that doesn't seem to be the case? ```find_by_doi()``` stills works and returns the first one of the above.

We could circumvent this problem by using ```validates :doi, uniqueness: true``` in all paper models, but that feels sloppy.

**Comment by philippbayer** [comment]
Turns out the rake task doesn't work because you can't just fiddle with ActiveRecord::Relation.

However, the snp-references are just stored in the SQL table snp_references, so how about I just do

```sql
SELECT DISTINCT * INTO new_table FROM snp_references;
DROP TABLE snp_references;
ALTER TABLE new_table RENAME TO snp_references;
```

We have 218,873 SNP references on the server so it shouldn't take very long, we might have errors in production for a few minutes. Yay or nay?

**Comment by tsujigiri** [comment]
If you put it into a transaction, there shouldn't be any errors. I'd say, go ahead. Also, adding a unique constraint before switching out the tables might be a good idea as well.

**Comment by philippbayer** [comment]
You're right, I've changed that. I can't deploy right now anyway  :P

**Comment by philippbayer** [comment]
Duplicate papers have been removed - 

```ruby
Snp.find_by_name("rs9939609").plos_papers.each do |u|
   if u.first_author.include? "Yan Guo"
     puts u.inspect
   end
end; nil
```

only prints

`<PlosPaper id: 1284, first_author: "Yan Guo", title: "The Fat Mass and Obesity Associated Gene, FTO, Is ...", doi: "10.1371/journal.pone.0027312", pub_date: "2011-11-18 00:00:00", created_at: "2012-02-06 00:12:36", updated_at: "2014-10-30 16:08:59", reader: 3786>`

once!
