### ISSUE TITLE
Yoong Kang Lim: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by yoongkang** [gedankenstuecke/snpr#206]
<p><br><blockquote>This issue was created by @yoongkang via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by yoongkang** [comment]
Oh, I didn't know this created an issue...

**Comment by philippbayer** [comment]
No worries :)
