### ISSUE TITLE
Adding a Code of Conduct

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/snpr#237]
I think we should add one. Even if our team is small and I think we didn't have any issues with this so far it would send a clear sign of what's (un)acceptable behaviour for us. I personally like the [Slidewinder CoC](http://www.slidewinder.io/docs/01_code_of_conduct.html). 

Any opinions on this?

**Comment by tsujigiri** [comment]
Sounds like a good idea. How about having it apply to the users as well, not only to the team?

**Comment by gedankenstuecke** [comment]
You mean as a CoC for opensnp.org itself instead of only using it for development? Sounds great to me! :+1:

**Comment by philippbayer** [comment]
Both sound good to me!
