### ISSUE TITLE
File Size Limit

### ISSUE THREAD

**Issue by gedankenstuecke** [gedankenstuecke/snpr#241]
A user tried to upload his whole genome(!) in VCF, which is ~500mb in size after compression and it failed with a 413 Request Entity Too Large. I personally think it would be okay if people upload their large WGS-VCFs as well, what do you guys think? 

If we agree we should increase the size limit?

**Comment by philippbayer** [comment]
All you'd have to do is to increase this number in line 1:

https://github.com/tsujigiri/opensnp.org-docker/blob/master/nginx-http.conf

How about 1GB?

**Comment by gedankenstuecke** [comment]
:+1: sounds good to me. 

p.s. yeah, lots of ideas.

**Comment by philippbayer** [comment]
Waiting for https://github.com/tsujigiri/opensnp.org-docker/pull/2

**Comment by gedankenstuecke** [comment]
Thanks, I also started to think about doing a CONTRIBUTING.md, I think it would be worthwhile to start one and have some easy bugs/features to implement for newcomers, because people now come up to me from time to time and ask how to participate best :-)

**Comment by philippbayer** [comment]
Yes a CONTRIBUTING.md would be good - Docker/swarm has a nice one: https://github.com/docker/swarm/blob/master/CONTRIBUTING.md

In a similar vein, I saw the [Humans TXT](http://humanstxt.org/) thing on the #MozWow tag, how about one of those? Would be a good place to thank financial contributions

**Comment by gedankenstuecke** [comment]
Absolutely, see #245 and #246
