### ISSUE TITLE
Champs coupons spam?

### ISSUE THREAD

**Issue by Treblesteph** [gedankenstuecke/snpr#244]
There are a couple of phenotypes and a user all called champs coupons which look like spam.

https://opensnp.org/picture_phenotypes/7
https://opensnp.org/picture_phenotypes/6
https://opensnp.org/users/3707

**Comment by philippbayer** [comment]
Thank you for reporting this!

We've had spam phenotypes in the past (I'm actually a little impressed people bother filling these out), back when this happened the first time we added a small warning to the signup that spam will be deleted. 

I have deleted these three entries. Again, thank you!
